package javaProgrammingPart3;

public class FibonacciSeries {

    public static void main(String[] args) {
        int n = 10;
//        printFibonacciSeriesBruteForce(n);
        for (int i = 0; i < n; i++) {
            System.out.print(fibonacciRecursion(i) + " ");
        }
    }

    /*
    1,1,2,3,5,8...
     */
    public static void printFibonacciSeriesBruteForce(int n) {

        int x = 1, y = 1, z;
        System.out.print(x + ",");
        System.out.print(y + ",");
        for (int i = 2; i < n; i++) {   //i=2 because it starts from 2nd index (0 & 1 index are 1)
            z = x + y;
            if (i != 2)
                System.out.print("," + z);
            else
                System.out.print(z);
            x = y;
            y = z;
        }
    }

    /*
    The fibonacci number is generated by adding the previous two numbers
    i.e F(0) = 1, F(1) = 1, and F(n) = F(n-1) + F(n-2)
    0,1,1,2,3,5,8...
     */
    public static int fibonacciRecursion(int n) {
        // F(0) = 1
        if (n == 0)
            return 0;
        // F(1) = F(2) = 1
        if (n == 1 || n == 2)
            return 1;

        return fibonacciRecursion(n - 2) + fibonacciRecursion(n - 1);
    }
}
